AsaludEcopetrol/Controllers/FIS/FIS_RIPSController.cs
using AsaludEcopetrol.BussinesManager;
using AsaludEcopetrol.Models;
using Aspose.Cells;
using ClosedXML.Excel;
using ECOPETROL_COMMON.ENTIDADES;
using ECOPETROL_COMMON.ENUM;
using ECOPETROL_COMMON.UTILOBJECTS;
using Facede;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;


namespace AsaludEcopetrol.Controllers.FIS
{
    public class FIS_RIPSController : Controller
    {

        #region  PROPIEDADES

        private SessionState _SesionVar;
        public SessionState SesionVar
        {
            get
            {
                if (_SesionVar == null)
                {
                    _SesionVar = new SessionState();
                }
                return _SesionVar;
            }
            set { _SesionVar = value; }
        }

        MessageResponseOBJ MsgRes = new MessageResponseOBJ();
        Facade BusClass = new Facade();
        #endregion

        public ActionResult CrearPrestador(int? idPrestador)
        {
            ViewBag.regionales = BusClass.GetRefRegion();
            management_fisPrestadoresResult prestador = new management_fisPrestadoresResult();
            List<management_fisPrestadores_sedesResult> listaSedes = new List<management_fisPrestadores_sedesResult>();

            try
            {
                if (idPrestador != null)
                {
                    prestador = BusClass.TraerPrestadorId(idPrestador);
                    listaSedes = BusClass.TraerPrestadorSedesId(idPrestador).Where(x => x.estado_sede == 1).ToList();
                }
            }
            catch (Exception ex)
            {
                var error = ex.Message;
            }

            ViewBag.id_prestador = idPrestador;

            Session["ListadoSedes"] = listaSedes;

            ViewBag.regionales = BusClass.TraerregionalesFis();

            return View(prestador);
        }

        public string ObtenerDepartamentos(int? regional)
        {
            string result = "<option value=''>- Seleccionar -</option>";

            List<management_fis_departamento_regionalResult> departamentos = new List<management_fis_departamento_regionalResult>();

            try
            {
                departamentos = BusClass.TraerDepartamentosFis(regional);
                foreach (var item in departamentos)
                {
                    result += "<option value='" + item.id_departamento + "'>" + item.nom_departamento + "</option>";
                }
            }
            catch (Exception ex)
            {
                var error = ex.Message;
            }

            return result;
        }

        public string ObtenerCiudades(int? departamento)
        {
            string result = "<option value=''>- Seleccionar -</option>";

            List<fis_rips_ciudad> departamentos = new List<fis_rips_ciudad>();

            try
            {
                departamentos = BusClass.TraerCiudadesFis(departamento);
                foreach (var item in departamentos)
                {
                    result += "<option value='" + item.id_ciudad + "'>" + item.nom_ciudad + "</option>";
                }
            }
            catch (Exception ex)
            {
                var error = ex.Message;
            }

            return result;
        }

        public string ValidarExistenciaPrestadorNit(string IDPrestador)
        {
            var resultado = "";
            fis_rips_prestadores lista = new fis_rips_prestadores();
            try
            {
                lista = BusClass.PrestadorxNit(Convert.ToString(IDPrestador));
                resultado = lista != null ? "ESTE NIT PRESTADOR YA EXISTE" : "";
            }
            catch (Exception ex)
            {
                var error = ex.Message;
                resultado = "ERROR EN LA CONSULTA";
            }
            return resultado;
        }

        public string ValidarExistenciaPrestadorCodHab(string codHab)
        {
            var resultado = "";
            List<fis_rips_prestadores> lista = new List<fis_rips_prestadores>();
            try
            {
                lista = BusClass.ConsultaPrestadoresFisCodHab(codHab, ref MsgRes);
                resultado = lista.Count() > 0 ? "ESTE CODIGO HABILITACIÓN YA EXISTE" : "";
            }
            catch (Exception ex)
            {
                var error = ex.Message;
                resultado = "ERROR EN LA CONSULTA";
            }
            return resultado;
        }

        public JsonResult CrearSedesPrestadorGuardar(Models.FIS.FIS_RIPS Model)
        {
            String mensaje = "";
            fis_rips_prestadores_sedes prestadorSedes = new fis_rips_prestadores_sedes();
            List<management_fisPrestadores_sedesResult> TotalSedes = new List<management_fisPrestadores_sedesResult>();
            fis_rips_prestadores prestador = new fis_rips_prestadores();

            int i = 0;
            int ultestado = 0;
            string result = "";

            try
            {
                prestador.nit = Model.nit;
                prestador.codigo_verfificacion = Model.codigo_verfificacion;
                prestador.codigo_SAP = Model.codigo_SAP;
                prestador.codigo_habilitacion = Model.codigo_habilitacion;
                prestador.razon_social = Model.razon_social;
                prestador.ciudad_proveedor = Model.ciudad_proveedor;
                prestador.departamento_proveedor = Model.departamento_proveedor;
                prestador.regional = Model.regional;
                prestador.direccion = Model.direccion;
                prestador.contacto_telefonico = Model.contacto_telefonico;
                prestador.correo_electronico = Model.correo_electronico;
                prestador.estado = Model.estado;
                prestador.tiene_mas_sedes = Model.tiene_mas_sedes;
                prestador.fecha_digita = DateTime.Now;
                prestador.usuario_digita = SesionVar.UserName;

                if (Model.id_prestador == 0 || Model.id_prestador == null)
                {
                    Model.id_prestador = BusClass.InsertarPrestadorFis(prestador);
                }
                else
                {
                    prestador.id_prestador = (int)Model.id_prestador;
                    BusClass.ActualizarDatosPrestador(prestador);
                }

                var codigo_habilitacion = Model.codigo_habilitacion_sede;
                var OtraSede = Model.codigo_otra_sede;

                var existe = BusClass.TraerprestadorSedeCodHabilitacion(OtraSede, codigo_habilitacion, Model.id_prestador);

                if (existe != 0)
                {
                    return Json(new { success = false, message = "ESTE CÓDIGO HABILITACIÓN Y CÓDIGO SEDE YA ESTÁN REGISTRADOS" }, JsonRequestBehavior.AllowGet);
                }

                prestadorSedes.id_prestador_sede = Model.id_prestador;
                prestadorSedes.codigo_habilitacion_sede = Model.codigo_habilitacion_sede;
                prestadorSedes.codigo_otra_sede = Model.codigo_otra_sede;
                prestadorSedes.ciudad_sede = Model.ciudad_sede;
                prestadorSedes.departamento_sede = Model.departamento_sede;
                prestadorSedes.regional_sede = Model.regional_sede;
                prestadorSedes.direccion_sede = Model.direccion_sede;
                prestadorSedes.contacto_telefonico_sede = Model.contacto_telefonico_sede;
                prestadorSedes.correo_electronico_sede = Model.correo_electronico_sede;
                prestadorSedes.usuario_digita = SesionVar.UserName;
                prestadorSedes.estado_sede = 0;
                prestadorSedes.fecha_digita = DateTime.Now;

                var idSede = BusClass.InsertarSedePrestadorFis(prestadorSedes);

                if (idSede != 0)
                {
                    TotalSedes = BusClass.TraerPrestadorSedesId(Model.id_prestador);
                }

                if (TotalSedes.Count() > 0)
                {
                    var j = 0;
                    foreach (var item in TotalSedes)
                    {
                        j++;
                        result += "<tr>";
                        result += "<td>" + item.id_sede + "</td>";
                        result += "<td>" + item.codigo_habilitacion_sede + "</td>";
                        result += "<td>" + item.codigo_otra_sede + "</td>";
                        result += "<td>" + item.regional_sede + "</td>";
                        result += "<td>" + item.departamento_sede + "</td>";
                        result += "<td>" + item.ciudad_sede + "</td>";
                        result += "<td>" + item.direccion_sede + "</td>";
                        result += "<td>" + item.contacto_telefonico_sede + "</td>";
                        result += "<td>" + item.correo_electronico_sede + "</td>";
                        result += "<td>" + item.fecha_digita + "</td>";
                        result += "<td>" + item.nombreDiigtaSedes + "</td>";
                        result += "<td class='text-center'>" +
                            "<a class='btn btn-xs button_Asalud_Rechazar' onclick='EliminarSede(" + item.id_sede + ")'><i class='glyphicon glyphicon-trash'></i>&nbsp; Eliminar</a>" +
                            "</td>";
                        result += "</tr>";
                    }
                }

                Session["ListadoSedes"] = TotalSedes;

                if (idSede != 0)
                {
                    mensaje = "SE INGRESÓ CORRECTAMENTE LA SEDE.";
                    return Json(new { success = true, message = mensaje, id = Model.id_prestador, tabla = result }, JsonRequestBehavior.AllowGet);

AsaludEcopetrol/Views/FIS_RIPS/CargarTigasContratosMasivo.cshtml
@{
    ViewBag.Title = "CARGUE MASIVO TIGAS CONTRATO";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
}

<div class="container">

    <div class="panel panel-default">

        <div class="panel-heading">
            <strong class="text-primary_asalud">ARCHIVOS AUXILIARES</strong>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-2">
                    <a class="btn button_Asalud_Aceptar" onclick="DescargarListaContratos()">LISTA CONTRATOS</a>
                </div>
                <div class="col-md-2">
                    <a class="btn button_Asalud_Aceptar" onclick="DescargarListaDetallados()">LISTA TIGAS</a>
                </div>

                <div class="col-md-2">
                    <a class="btn button_Asalud_Aceptar" onclick="DescargarArchivoPlantilla()">PLANTILLA CARGUE</a>
                </div>
            </div>
        </div>
    </div>
    <br />

    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="text-primary_asalud">CARGUE</strong>
        </div>
        <br />
        <form id="formContratos">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4">
                        <label class="text-secondary_asalud">Seleccione archivo</label>
                        <input type="file" id="archivo" name="archivo" class="form-control" onchange="ValidacionArchivo()" required />
                    </div>
                    <br />
                    <div class="col-md-2">
                        <a class="btn button_Asalud_Guardar" onclick="ValidarDatos()">CARGAR</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="~/Scripts/validate.js"></script>
<script>

    function ValidacionArchivo() {
        var fileInput = document.getElementById('archivo');
        var filePath = fileInput.value;
        var allowedExtensions = /(\.xls|\.xlsx)$/i;
        if (!allowedExtensions.exec(filePath)) {
            alert('Por favor, solo subir archivos que contengan la extension .xls o .xlsx');
            fileInput.value = '';
            return false;
        } else {
            return true;
        }
    }

    function ValidarDatos() {
        var validacion = $("#formContratos").validate();
        if (validacion.form()) {
            Enviardata();
        }
    }

    function Enviardata(){

        var formData = new FormData($("form")[0]);
        var archivo = $("#archivo").get(0).files[0];
        formData.append("archivo", archivo); // Enviar solo el primer archivo

        $.ajax({
            url: "@Url.Action("GuardarTigasContratoMasivo")",
            type: "post",
            data: formData,
            method: "post",
            processData: false,
            contentType: false,

            success: function (data) {
                alert(data.mensaje);
                if (data.rta == 1) {
                    location.reload();
                }
            }
        });
    }

    function DescargarListaContratos(){
         var URL2 = "@Url.Action("ExcelDescargarContratosExistentes", "FIS_RIPS")";
        window.open(URL2, '', 'width=450,height =150,left =50,top =550,toolbar =yes');
    }

    function DescargarArchivoPlantilla() {
         var url = "@Url.Action("VerPlantillaCargueTIGASContrato", "FIS_RIPS")";
        popupWindow = window.open(url, '', 'height=150,width=500,left=50,top=550,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no, status=yes')
    }

    function DescargarListaDetallados(){
         var url = "@Url.Action("ExcelDescargarTigasDetallados", "FIS_RIPS")";
        popupWindow = window.open(url, '', 'height=150,width=500,left=50,top=550,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no, status=yes')
    }
</script>

AsaludEcopetrol/Views/FIS_RIPS/CargueMasivoDetalles.cshtml
@{
    ViewBag.Title = "CARGUE MASIVO DETALLES";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="text-primary_asalud">PLANTILLA</strong>
        </div>
        <div class="panel-body">
            <a class="button_Asalud_Aceptar" onclick="descargarPlantilla();">Descargar plantilla</a>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="text-primary_asalud">CARGUE</strong>
        </div>
        <div class="panel-body">
            <form id="formularioIngreso">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="text-secondary_asalud">Regional</label>
                            <select id="regional" name="regional" class="form-control select2" required>
                                <option value="">-Seleccione-</option>
                                @foreach (ECOPETROL_COMMON.ENTIDADES.Ref_regional item in ViewBag.regional)
                                {
                                    <option value="@item.id_ref_regional">@item.nombre_regional</option>
                                }
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label class="text-secondary_asalud">Seleccione archivo</label>
                            <input type="file" id="archivo" name="archivo" class="form-control" onchange="ValidacionArchivo()" required />
                        </div>
                        <br />
                        <div class="col-md-2">
                            <a class="btn button_Asalud_Aceptar" onclick="ValidarCargue()">CARGAR</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/Scripts/validate.js"></script>
<script>

    $(document).ready(function () {
        $('.select2').select2({
            width: '100%'
        });
    })

    function ValidacionArchivo() {
        var fileInput = document.getElementById('archivo');
        var filePath = fileInput.value;
        var allowedExtensions = /(\.xls|\.xlsx)$/i;
        if (!allowedExtensions.exec(filePath)) {
            alert('Por favor, solo subir archivos que contengan la extension .xls o .xlsx');
            fileInput.value = '';
            return false;
        } else {
            return true;
        }
    }

    function ValidarCargue() {
        var validacion = $("#formularioIngreso").validate();
        if (validacion.form()) {
            Enviardata();
        }
    }

    function Enviardata() {

        var formData = new FormData($("form")[0]);
        formData.append("regional", $("#regional").val());

        var archivo = $("#archivo").get(0).files[0];
        formData.append("archivo", archivo); // Enviar solo el primer archivo

        LoadingShow();
        $.ajax({

            url: "@Url.Action("GuardarMasivoDetalles", "FIS_RIPS")",
            method: "post",
            data: formData,
            type: "post",
            contentType: false,
            processData: false,
            success: function (data) {
                alert(data.mensaje);
                LoadingHide();

                if (data.rta != 0) {
                    location.reload();
                }
            }
        })
    }

    function descargarPlantilla() {
        var url = "@Url.Action("VerPlantillaCargueDetalles", "FIS_RIPS")";
        popupWindow = window.open(url, '', 'height=150,width=500,left=50,top=550,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no, status=yes')
    }

</script>

AsaludEcopetrol/Views/FIS_RIPS/CargueMasivoIVM.cshtml
@{
    ViewBag.Title = "CARGUE MASIVO VIM";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
}


<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="text-primary_asalud">CARGUE</strong>
        </div>
        <div class="panel-body">
            <form id="formularioIngreso">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="text-secondary_asalud">Seleccione archivo</label>
                            <input type="file" id="archivo" name="archivo" class="form-control" onchange="ValidacionArchivo()" required />
                        </div>
                        <br />
                        <div class="col-md-2">
                            <a class="btn button_Asalud_Aceptar" onclick="ValidarCargue()">CARGAR</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/Scripts/validate.js"></script>
<script>

    $(document).ready(function () {
        $('.select2').select2({
            width: '100%'
        });
    })

    function ValidacionArchivo() {
        var fileInput = document.getElementById('archivo');
        var filePath = fileInput.value;
        var allowedExtensions = /(\.xls|\.xlsx)$/i;
        if (!allowedExtensions.exec(filePath)) {
            alert('Por favor, solo subir archivos que contengan la extension .xls o .xlsx');
            fileInput.value = '';
            return false;
        } else {
            return true;
        }
    }

    function ValidarCargue() {
        var validacion = $("#formularioIngreso").validate();
        if (validacion.form()) {
            Enviardata();
        }
    }

    function Enviardata() {

        var formData = new FormData($("form")[0]);
        var archivo = $("#archivo").get(0).files[0];
        formData.append("archivo", archivo); // Enviar solo el primer archivo

        LoadingShow();
        $.ajax({

            url: "@Url.Action("GuardarMasivoIVM", "FIS_RIPS")",
            method: "post",
            data: formData,
            type: "post",
            contentType: false,
            processData: false,
            success: function (data) {
                alert(data.mensaje);
                LoadingHide();

                if (data.rta != 0) {
                    location.reload();
                }
            }
        })
    }

</script>

AsaludEcopetrol/Views/FIS_RIPS/CreacionCUPS.cshtml
@model ECOPETROL_COMMON.ENTIDADES.fis_rips_cups

@{
    ViewBag.Title = "CREACIÓN CUPS";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="text-primary_asalud">CUPS</strong>
        </div>
        <div class="panel-body">
            <form id="formularioIngreso">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-3">
                            <input type="hidden" name="id_cups" id="id_cups" value="@ViewBag.id_cups" />
                            <label class="text-secondary_asalud">Código CUPS</label>
                            <input type="text" class="form-control" id="codigo_cups" name="codigo_cups" maxlength="12" value="@Model.codigo_cups" required />
                        </div>
                        <div class="col-md-3">
                            <label class="text-secondary_asalud">Descripción</label>
                            <input type="text" class="form-control" style="width:100%;" id="descripcion" maxlength="199" name="descripcion" value="@Model.descripcion" required />
                        </div>
                        <div class="col-md-3">
                            <label class="text-secondary_asalud">Manual tarifario</label>
                            <select id="manual" name="manual" class="form-control" required>
                                <option value="">--Seleccione--</option>
                                <option value="SOAT">SOAT</option>
                                <option value="ISS">ISS</option>
                                <option value="ECP">ECP</option>
                                <option value="PROPIAS">PROPIAS</option>
                                <option value="OTRO">OTRO</option>
                            </select>
                        </div>

                        <div class="col-md-3">
                            <label class="text-secondary_asalud">ACTIVO</label>
                            <select id="estado" name="estado" class="form-control" required>
                                <option value="">-Seleccione-</option>
                                <option value="1">SI</option>
                                <option value="2">NO</option>
                            </select>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="text-primary_asalud">GUARDADO</strong>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 text-center">
                    <button onclick="ValidarFormulario()" class="button_Asalud_Guardar">GUARDAR</button>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Scripts/validate.js"></script>

<script>

    $(document).ready(function () {

        $('.select2').select2({
            width: '100%',
            height: '100%'
        });

        $('.solo-numeros').keyup(function () {
            this.value = (this.value + '').replace(/[^0-9]/g, '');
        });

        var idCups = "@Model.id_cups";
        if (idCups != 0 && idCups != null && idCups != "") {
            PintarCampos();
        }
    });


    $("#codigo_cups").change(function () {
        var value = this.value;

        if (value.length < 6) {
            this.setCustomValidity('El código debe tener al menos 6 caracteres.');
        } else if (value.length > 12) {
            this.setCustomValidity('El código no debe exceder los 12 caracteres.');
        } else {
            this.setCustomValidity('');
        }
    });

    function PintarCampos() {
        $("#manual").val("@Model.manual").trigger("change");
        $("#estado").val("@Model.estado").trigger("change");
    }

    function ValidarFormulario() {
        var validar = $("#formularioIngreso").validate();
        if (validar.form()) {
            GuardarDatos();
        }
    }

    function GuardarDatos() {

        var formData = new FormData($("#formularioIngreso")[0]);

        formData.append("id_cups", $("#id_cups").val());
        formData.append("codigo_cups", $("#codigo_cups").val());
        formData.append("descripcion", $("#descripcion").val());
        formData.append("manual", $("#manual").val());
        formData.append("estado", $("#estado").val());
        
        LoadingShow();
        $.ajax({
            url: '@Url.Action("GuardarCups", "FIS_RIPS")',
            data: formData,
            method: "POST",
            processData: false,
            contentType: false,

            success: function (response) {
                LoadingHide();
                alert(response.mensaje);
                if (response.rta == 1) {
                    location.href = "@Url.Action("TableroCups", "FIS_RIPS")";
                }
            },
            error: function (xhr, status, error) {
                LoadingHide();
            }
        });
    }

</script>

AsaludEcopetrol/Views/FIS_RIPS/CrearCie10FIS.cshtml
@{
    ViewBag.Title = "CREACIÓN CIE10";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
}


<div class="container">
    <div class="panel panel-default">

        <div class="panel-heading">
            <strong class="text-primary_asalud">CREACIÓN CIE10</strong>
        </div>
        <br />
        <form id="formCie">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-3">
                        <label class="text-secondary_asalud">Codigo</label>
                        <input type="text" class="form-control" id="codigo" name="codigo" value="@ViewBag.codigo" required maxlength="50" />
                    </div>

                    <div class="col-md-7">
                        <label class="text-secondary_asalud">Descripción</label>
                        <input type="text" class="form-control" id="descripcion" name="descripcion" value="@ViewBag.descripcion" required maxlength="599" />
                    </div>
                    <br />

                    <div class="COL-MD-2">
                        <a class="btn button_Asalud_Guardar" onclick="ValidarDatos()">GUARDAR</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="~/Scripts/validate.js"></script>
<script>


    @*$("#codigo").on("input", function () {
        var codigo = $(this).val();

        $.ajax({
            url: "@Url.Action("validarCie10Codigo", "FIS_RIPS")",
            type: "post",
            data: { codigo: codigo },
            success: function (data) {
                if (data != "") {
                    $("#codigo").val("");
                    $("#codigo").focus();
                    alert(data);
                }
            }
        })
    });


    $("#descripcion").on("input", function () {
        var descripcion = $(this).val();

        $.ajax({
            url: "@Url.Action("validarCie10Descripcion", "FIS_RIPS")",
            type: "post",
            data: { descripcion: descripcion },
            success: function (data) {
                if (data != "") {
                    $("#descripcion").val("");
                    $("#descripcion").focus();
                    alert(data);
                }
            }
        })
    });*@

    function ValidarDatos() {
        var validacion = $("#formCie").validate();
        if (validacion.form()) {
            Enviardata();
        }
    }

    function Enviardata(){

        var formData = new FormData($("form")[0]);
        formData.append("codigo", $("#codigo").val());
        formData.append("descripcion", $("#descripcion").val());

        $.ajax({
            url: "@Url.Action("GuardarCIE10FIS")",
            type: "post",
            data: formData,
            method: "post",
            processData: false,
            contentType: false,

            success: function (data) {
                alert(data.mensaje);
                if (data.rta == 1) {
                    location.href = "@Url.Action("TableroCIE10FIS", "FIS_RIPS")";
                }
            }
        });
    }

</script>