AsaludEcopetrol/Models/InicioSesion/GestionInterna.cs
using AsaludEcopetrol.BussinesManager;
using ECOPETROL_COMMON.UTILOBJECTS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ECOPETROL_COMMON.ENTIDADES;

namespace AsaludEcopetrol.Models.InicioSesion
{
    public class GestionInterna
    {
        #region PROPIEDADES

        private Facede.Facade _BusClass;
        public Facede.Facade BusClass
        {
            get
            {
                if (_BusClass != null)
                {
                    return _BusClass;
                }
                else
                {
                    return _BusClass = new Facede.Facade();
                }

            }
            set { _BusClass = value; }
        }

        private SessionState _SesionVar;
        public SessionState SesionVar
        {
            get
            {
                if (_SesionVar == null)
                {
                    _SesionVar = new SessionState();
                }
                return _SesionVar;
            }
            set { _SesionVar = value; }
        }

        MessageResponseOBJ MsgRes = new MessageResponseOBJ();

        #endregion

        #region FUNCIONES 

        public List<ref_gestion_interna> GetGestionInternaList()
        {
            return BusClass.GetGestionInternaList();
        }

        public ref_gestion_interna GetGestionInternaById(int idgestion)
        {
            return BusClass.GetGestionInternaById(idgestion);
        }

        #endregion
    }
}

AsaludEcopetrol/Models/InicioSesion/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Security.Cryptography;
using System.Text;
using ECOPETROL_COMMON.UTILOBJECTS;
using ECOPETROL_COMMON.ENTIDADES;
using System.Configuration;

namespace AsaludEcopetrol.Models.InicioSesion
{
    public class Login
    {
        #region PROPIEDADES

        private Facede.Facade _BusClass;
        public Facede.Facade BusClass
        {
            get
            {
                if (_BusClass != null)
                {
                    return _BusClass;
                }
                else
                {
                    return _BusClass = new Facede.Facade();
                }

            }
            set { _BusClass = value; }
        }

        MessageResponseOBJ MsgRes = new MessageResponseOBJ();

        [Required]
        [Display(Name = "Usuario:")]
        public string usuario { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña:")]
        public string contraseña { get; set; }

        [Display(Name = "Recordar en este equipo")]
        public bool RememberMe { get; set; }

        public String numero_documento { get; set; }

        public String usuarioClave { get; set; }
        
        [Display(Name = "Código:")]
        public string codigo { get; set; }

        #endregion

        #region EVENTOS PRIVADOS


        public int SessionTimeout
        {
            get
            {
                int timeout = 20; // Valor predeterminado de 20 minutos (o cualquier valor que desees)
                int.TryParse(ConfigurationManager.AppSettings["SessionTimeoutMinutes"], out timeout);
                return timeout;
            }
            set
            {
                // Aquí puedes agregar la lógica para cambiar la configuración si es necesario.
                // En general, no se cambia el tiempo de sesión en tiempo de ejecución.
            }
        }


        private static String GetSHA1(String _ConvertPassword)
        {
            SHA1 _sha1 = SHA1Managed.Create();
            ASCIIEncoding _encoding = new ASCIIEncoding();
            Byte[] _stream = null;
            StringBuilder sb = new StringBuilder();
            _stream = _sha1.ComputeHash(_encoding.GetBytes(_ConvertPassword));
            for (int i = 0; i < _stream.Length; i++) sb.AppendFormat("{0:x2}", _stream[i]);
            return sb.ToString();
        }

        #endregion

        #region METODOS

        public List<sis_usuario> ValidaIngreso(String _usuario, String _contraseña)
        {

            sis_usuario auditor = new sis_usuario();
            auditor.usuario = _usuario;
            auditor.contraseña = _contraseña != "temporal" ? GetSHA1(_contraseña) : _contraseña;

            return BusClass.ValidaIngreso(auditor, ref MsgRes);
        }

        public sis_usuario ValidaIngresoClave(String _usuario, String documento)
        {
            sis_usuario auditor = new sis_usuario();
            auditor.usuario = _usuario;
            auditor.numero_documento = documento;

            return BusClass.ValidaIngresoClave(auditor, ref MsgRes);
        }

        public void ActualizaEstadoUsuario(sis_usuario ObjUsuario, ref MessageResponseOBJ MsgRes)
        {
            BusClass.ActualizaEstadoUsuario(ObjUsuario, ref MsgRes);
        }

        public List<sis_usuario> BuscaAuditorUsu(String strUsuario, ref MessageResponseOBJ MsgRes)
        {
            return BusClass.BuscaAuditorUsu(strUsuario, ref MsgRes);
        }
        public List<ManagementPrestadoresAlertasFechaResult> ManagmentAlertas(ref MessageResponseOBJ MsgRes)
        {
            return BusClass.ManagmentAlertas(ref MsgRes);
        }
        #endregion
    }
}

AsaludEcopetrol/Controllers/InicioSesion/GestionInternaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AsaludEcopetrol.Models;
using ECOPETROL_COMMON.ENTIDADES;

namespace AsaludEcopetrol.Controllers.InicioSesion
{
    public class GestionInternaController : Controller
    {
        
        public ActionResult gestioninterna()
        {
            Models.InicioSesion.GestionInterna Model = new Models.InicioSesion.GestionInterna();
            ViewBag.gestioninterna = Model.GetGestionInternaList();
            return View();
        }

        public JsonResult GetDatosGestion(int idgestioninterna)
        {
            Models.InicioSesion.GestionInterna Model = new Models.InicioSesion.GestionInterna();
            ref_gestion_interna obj = Model.GetGestionInternaById(idgestioninterna);
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

    }
}

AsaludEcopetrol/Controllers/InicioSesion/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ECOPETROL_COMMON.UTILOBJECTS;
using ECOPETROL_COMMON.ENTIDADES;
using AsaludEcopetrol.BussinesManager;
using System.Web.Routing;
using Facede;
using ECOPETROL_COMMON.ENUM;
using System.IO;
using Microsoft.Reporting.WebForms;
using System.Security.Principal;
using System.Text;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Net.Security;
using System.Net.Mail;
using System.Configuration;
using System.Net.Http;
using System.Threading.Tasks;
using System.Net.Configuration;

namespace AsaludEcopetrol.Controllers.InicioSesion
{

    public class UsuarioController : Controller
    {

        #region PROPIEDADES

        private SessionState _SesionVar;
        public SessionState SesionVar
        {
            get
            {
                if (_SesionVar == null)
                {
                    _SesionVar = new SessionState();
                }
                return _SesionVar;
            }
            set { _SesionVar = value; }
        }

        Facade BusClass = new Facade();

        #endregion

        #region EVENTOS PRIVADOS


        #endregion

        #region METODOS


        MessageResponseOBJ MsgRes = new MessageResponseOBJ();
        // GET: Usuario

        public ActionResult Login()
        {
            ViewBag.logo = BusClass.GetParametro("Logo");
            ViewBag.sami = BusClass.GetParametro("SAMIFIS");
            ViewBag.hsflogo = BusClass.GetParametro("HSFLOGO");
            ViewBag.logoAsalud = BusClass.GetParametro("LOGO ASALUD SELLO");
            ViewBag.logoSami = BusClass.GetParametro("LOGOSAMI");

            return View();
        }

        public ActionResult Login2()
        {
            return View();
        }

        public ActionResult LoginCerrado()
        {
            return View();
        }

        public ActionResult Inicio()
        {
            ViewBag.rol = SesionVar.ROL;
            List<Management_sis_actividad_recienteResult> ListActividadReciente = BusClass.GetListActividadReciente();
            ListActividadReciente = ListActividadReciente.Where(l => l.horas <= 12).ToList();
            ViewBag.actividadReciente = ListActividadReciente.OrderBy(l => l.minutos).ToList();
            System.GC.Collect();
            System.GC.WaitForFullGCComplete();

            ViewBag.proyectos = BusClass.ChatBotProyectos();

            return View(ListActividadReciente);
        }


        public string ObtenerOpciones(int? tipo, int? idProyecto, int? idProceso, int? idsubProceso, int? idPregunta)
        {
            string result = "";
            List<Management_chatbot_ref_proyectosResult> proyecto = new List<Management_chatbot_ref_proyectosResult>();
            List<Management_chatbot_ref_procesosResult> procesos = new List<Management_chatbot_ref_procesosResult>();
            List<Management_chatbot_ref_subprocesosResult> subprocesos = new List<Management_chatbot_ref_subprocesosResult>();
            List<Management_chatbot_ref_preguntasResult> preguntas = new List<Management_chatbot_ref_preguntasResult>();
            List<Management_chatbot_ref_respuestasResult> respuestas = new List<Management_chatbot_ref_respuestasResult>();

            try
            {
                if (tipo == 0)
                {
                    proyecto = BusClass.ChatBotProyectos();

                    result = "<label class='text-secondary_asalud'>Seleccione el proyecto</label>";
                    result += "<input type='hidden' id='tipoPreguntaAnterior' name='tipoPreguntaAnterior' value='" + 0 + "'>";
                    //result += "<input type='hidden' id='respuestaAnterior' name='respuestaAnterior' value='" + 0 + "'>";

                    foreach (var item in proyecto)
                    {
                        result += " <div class='col-md-12 text-center'>";
                        result += " <a class='btn botonChat' onclick='LlenarOpcionesMensaje(1, " + item.id_chatbot_ref_proyecto + ", 1)'>" + item.descripcion + "</a>";
                        result += " </div>";
                        result += " <br />";
                        result += " <br />";
                    }
                }

                else if (tipo == 1)
                {
                    procesos = BusClass.ChatBotProcesos(idProyecto);

                    result = "<label class='text-secondary_asalud'>Seleccione el proceso</label>";

                    //result += " <div class='col-md-12 text-center'>";
                    //result += "<a class='btn botonAnterior' onclick='LlenarOpcionesMensaje(" + 0 + ", " + 0 + ")'> Volver al menú anterior </a>";
                    //result += " </div>";
                    //result += " <br />";
                    //result += " <br />";

                    result += "<input type='hidden' id='tipoPreguntaAnterior' name='tipoPreguntaAnterior' value='" + (tipo - 1) + "'>";
                    //result += "<input type='hidden' id='respuestaAnterior' name='respuestaAnterior' value='" + respuesta + "'>";

                    foreach (var item in procesos)
                    {
                        result += " <div class='col-md-12 text-center'>";
                        result += " <a class='btn botonChat' onclick='LlenarOpcionesMensaje(2, " + item.id_chatbot_ref_proceso + ", 1)'>" + item.descripcion + "</a>";
                        result += " </div>";
                        result += " <br />";
                        result += " <br />";

                    }
                }

                else if (tipo == 2)
                {
                    subprocesos = BusClass.ChatBotSubProcesos(idProceso);

                    result = "<label class='text-secondary_asalud'>Seleccione el sub proceso</label>";

                    result += " <div class='col-md-12 text-center'>";
                    result += "<a class='btn botonAnterior' onclick='LlenarOpcionesMensaje(1, " + idProceso + ")'> Volver al menú anterior </a>";
                    result += " </div>";
                    result += " <br />";
                    result += " <br />";

                    result += "<input type='hidden' id='tipoPreguntaAnterior' name='tipoPreguntaAnterior' value='" + (tipo - 1) + "'>";
                    //result += "<input type='hidden' id='respuestaAnterior' name='respuestaAnterior' value='" + respuesta + "'>";


                    foreach (var item in subprocesos)
                    {
                        result += " <div class='col-md-12 text-center'>";
                        result += " <a class='btn botonChat' onclick='LlenarOpcionesMensaje(3, " + item.id_chatbot_ref_subproceso + ", 1)'>" + item.descripcion + "</a>";
                        result += " </div>";
                        result += " <br />";
                        result += " <br />";
                    }
                }

                else if (tipo == 3)
                {
                    preguntas = BusClass.ChatBotPreguntas(idsubProceso);

                    result = "<label class='text-secondary_asalud'>Preguntas: </label>";

                    result += " <div class='col-md-12 text-center'>";
                    result += "<a class='btn botonAnterior' onclick='LlenarOpcionesMensaje(2, " + idsubProceso + ")'> Volver al menú anterior </a>";
                    result += " </div>";
                    result += " <br />";
                    result += " <br />";

                    result += "<input type='hidden' id='tipoPreguntaAnterior' name='tipoPreguntaAnterior' value='" + (tipo - 1) + "'>";
                    //result += "<input type='hidden' id='respuestaAnterior' name='respuestaAnterior' value='" + respuesta + "'>";
                    //result += "<input type='hidden' id='subProceso' name='subProceso' value='" + respuesta + "'>";

                    foreach (var item in preguntas)
                    {
                        result += " <div class='col-md-12 text-center'>";

                        result += " <a class='btn botonChat' onclick='LlenarOpcionesMensaje(4, " + item.id_chatbot_ref_pregunta + ", 1)'>" + item.descripcion + "</a>";

                        result += " </div>";
                        result += " <br />";
                        result += " <br />";
                    }
                }

                else if (tipo == 4)
                {
                    respuestas = BusClass.ChatBotRespuestas(idPregunta);

                    result = "<label class='text-secondary_asalud'>Respuestas: </label>";

                    result += " <div class='col-md-12 text-center'>";
                    result += "<a class='btn botonAnterior' onclick='LlenarOpcionesMensaje(3, " + idPregunta + ")'> Volver al menú anterior </a>";
                    result += " </div>";
                    result += " <br />";
                    result += " <br />";

                    result += "<input type='hidden' id='tipoPreguntaAnterior' name='tipoPreguntaAnterior' value='" + (tipo - 1) + "'>";
                    //result += "<input type='hidden' id='respuestaAnterior' name='respuestaAnterior' value='" + respuesta + "'>";

                    foreach (var item in respuestas)
                    {
                        result += " <div class='col-md-12 text-center'>";

                        result += " <a class='btn botonChat'>" + item.descripcion + "</a>";
                        result += " </div>";
                        result += " <br />";
                        result += " <br />";
                    }
                }
            }

            catch (Exception ex)
            {
                var error = ex.Message;
            }

            return result;
        }



        public ActionResult CambiarClave()
        {
            return View();
        }

        public ActionResult CambiarClave2()
        {
            return View();

AsaludEcopetrol/Views/Usuario/CambiarClave2.cshtml
@{
    ViewBag.Title = "CambiarClave2";

}

<script language="javascript" type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/jquery.validate.min.js"></script>
<script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/localization/messages_es.js"></script>



<div class="panel panel-default">
    <div class="panel-heading">
        <strong class="text-primary_asalud">Validación</strong>
    </div>
    <div class="panel-body">

        <div class="panel-body" id="panel_formulario">
            <form class="animated fadeInDown" id="formulario">  

                <div class="row">

                    <div class="col-sm-12 form-group">
                        <label class="text-secondary_asalud">Documento</label>
                        <input type="text" class="form-control solo-numero solo-numero2 solo-numero3 " name="txtDocumento" id="txtDocumento" maxlength="16" required autocomplete="off" />
                    </div>
                    <div class="col-sm-12 form-group">
                        <label class="text-secondary_asalud">Usuario</label>
                        <input rows="4" cols="100" type="text" class="form-control" name="txtusuario" id="txtusuario" required maxlength="50" autocomplete="off" />
                    </div>

                </div>


                <div class="row">
                    <div class="col-sm-12">
                        <button class="button_Asalud_Aceptar" type="button" onclick="ValidarFormulario()">Buscar</button>

                    </div>
                </div>
                <div style="display:none">

                </div>

            </form>
        </div>
    </div>
</div>

<div id="loader"></div>
<div id="dialog"></div>
<div id="container" style="min-height: 1px">
    <div id="content" style="min-height: 1px">
        <div id="DivLoadingPage"></div>
        <div class="modal fade" data-backdrop="static" data-keyboard="false" id="SpinnerCarga">
            <img id="imgloader" src="~/Resources/cargando.gif" alt="Loading">
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

      $('.select2').select2({
            width: '100%'
        });

        $(".datepickerr").kendoDatePicker({
            format: "MM/dd/yyyy",
        });
        $(".k-input").attr('readonly', true);

        $('.solo-numero').keyup(function () {
            this.value = (this.value + '').replace(/[^0-9.]/g, '');
        });


        $('.solo-numero2').keydown(function () {
            this.value = (this.value + '').replace(/[^0-9.]/g, '');
        });


        $('.solo-numero3').focusout(function () {
            this.value = (this.value + '').replace(/[^0-9.]/g, '');

        });

    })

    function LoadingShow() {
        $("#SpinnerCarga").modal();
        $("#SpinnerCarga").modal({ backdrop: 'static', keyboard: false });
        $("#SpinnerCarga").modal('show');
    }

    function LoadingHide() {
        $("#SpinnerCarga").modal('hide');
    }


     function ValidarFormulario() {
         var validator = $("#formulario").validate(
             {
                 rules: {
                     txtDocumento: {
                         required: true,
                     }
                 }

             }

         );
        if (validator.form()) {

            GuardarDatos();
        }
     }


    function GuardarDatos() {

        var ff = $("#txtusuario").val();

        var formData = new FormData($("form")[0]);

        formData.append("usuarioClave", $("#txtusuario").val());
        formData.append("numero_documento", $("#txtDocumento").val());

        LoadingShow();
        $.ajax({
            url: "@Url.Action("SaveValidarUsuario", "Usuario")",
            type: "post",
            data: formData,
            method: 'POST',
            contentType: false,
            processData: false,

            success: function (response) {

                if (response.success) {
                    if (response.opc == 1) {
                        var laURLDeLaVista = '@Url.Action("GestionCambiodeclave")?ID=' + response.id + "&codigo=" + response.codigo;

                        $.ajax({
                            cache: false,
                            async: true,
                            type: "GET",
                            url: laURLDeLaVista,
                            data: {},
                            success: function (response) {
                                $("#myModal1").modal('show');
                                $('#resultado1').html('');
                                $('#resultado1').html(response);
                                LoadingHide();

                            }
                        });
                    }
                }
                else {
                    alert(response.message);
                    LoadingHide();
                }
            }

        })
    }

</script>
<style>
    #pnlcargararchivo {
        margin-top: 5%;
    }

    label.error {
        background-color: indianred;
        color: white;
        font-size: 13px;
        font-weight: bold;
        float: left;
        width: 100%;
        text-align: justify;
        font-weight: bold;
    }

    .Error {
        color: #800000;
        font-size: small;
        font-weight: bold;
    }

    .Tamaño {
        height: 200px;
    }

    .TamañoImag {
        height: 200px;
        position: center;
    }

    .TamañoDiv {
        position: page;
        /*width:1100px;*/
    }

    .btn-glyphicon {
        padding: 8px;
        background: #ffffff;
        margin-right: 4px;
    }

    .icon-btn {
        padding: 1px 15px 3px 2px;
        border-radius: 50px;
    }
</style>

AsaludEcopetrol/Views/Usuario/ControlErrores.cshtml
@{
    ViewBag.Title = "¡Atención!";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
}



<div class="alert alert-danger text-center">
    @ViewBag.mensaje;
</div>

AsaludEcopetrol/Views/Usuario/GestionCambiodeclave.cshtml
@{
    ViewBag.Title = "GestionCambiodeclave";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<div class="panel panel-default">
    <div class="panel-heading">
        <strong class="text-primary_asalud">CAMBIO DE CLAVE</strong>
    </div>
    <div class="panel-body">

        <div class="panel-body" id="panel_formulario">
            <form class="animated fadeInDown" id="formulario">

                <div class="row">
                    <div class="alert alert-info">
                        <strong>Alerta!</strong> El código fue enviado  a su correo corporativo!.
                    </div>
                    <div class="col-sm-12 form-group">
                        <label class="text-secondary_asalud">Código</label>
                        <input rows="4" cols="100" type="text" class="form-control" name="txtCodigo" id="txtCodigo" required maxlength="6" onchange="Validar()" />
                    </div>
                    <panel></panel>
                    <div class="col-sm-12 form-group">
                        <label class="text-secondary_asalud">Nueva contraseña</label>
                        <input rows="4" cols="100" type="password" class="form-control" name="txtcontraseña" id="txtcontraseña" required maxlength="50" onchange="CheckValidAmount(this.value)" />
                    </div>
                    <div class="col-sm-12 form-group">
                        <label class="text-secondary_asalud">Confirmar contraseña</label>
                        <input rows="4" cols="100" type="password" class="form-control" name="txtNcontraseña" id="txtNcontraseña" required maxlength="50" onchange="validarContraseñas(this.value)" />
                    </div>

                </div>


                <div class="row">
                    <div class="col-sm-12">
                        <button class="button_Asalud_Aceptar" type="button" onclick="ValidarFormulario()">Guardar</button>

                    </div>
                </div>
                <div style="display:none">
                    <input class="form-control" type="text" name="id_usuario" id="id_usuario" value="@ViewBag.id_usuario" />
                    <input class="form-control" type="text" name="codigo" id="codigo" value="@ViewBag.codigo" />
                </div>

            </form>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {

      $('.select2').select2({
            width: '100%'
        });

        $(".datepickerr").kendoDatePicker({
            format: "MM/dd/yyyy",
        });
        $(".k-input").attr('readonly', true);

        $('.solo-numero').keyup(function () {
            this.value = (this.value + '').replace(/[^0-9.]/g, '');
        });

        $('.solo-numero2').keydown(function () {
            this.value = (this.value + '').replace(/[^0-9.]/g, '');
        });

        $('.solo-numero3').focusout(function () {
            this.value = (this.value + '').replace(/[^0-9.]/g, '');
        });

    })


     function ValidarFormulario() {
         var validator = $("#formulario").validate(
             {
                 rules: {
                     txtCodigo: {
                         required: true,
                     }
                 }

             }

         );
        if (validator.form()) {

            GuardarDatos();
        }
     }


    function GuardarDatos() {

        var ff = $("#txtusuario").val();

        var formData = new FormData($("form")[0]);

        formData.append("id_usuario", $("#id_usuario").val());
        formData.append("contraseñaNueva", $("#txtcontraseña").val());

        LoadingShow();
        $.ajax({
            url: "@Url.Action("SaveCambiarClave2", "Usuario")",
            type: "post",
            data: formData,
            method: 'POST',
            contentType: false,
            processData: false,

            success: function (response) {
                LoadingHide();
                if (response.success) {


                    alert(response.message);
                    location.reload();
                }
                else {

                    alert(response.message);
                }

            }
        })
    }

    function Validar() {

        var value1 = $("#txtCodigo").val();
        var value2 = $("#codigo").val();

        if (value1 != value2)
        {
            alert("Código incorrecto...");
            $("#txtCodigo").val("");
            $("#txtcontraseña").val("");
            $("#txtNcontraseña").val("");
        }
    };
    function validarContraseñas() {

        var value1 = $("#txtcontraseña").val();
        var value2 = $("#txtNcontraseña").val();

        if (value1 != value2) {
            alert("Contraseñas no son iguales...");
            $("#txtNcontraseña").val("");
        }
    };


    function CheckValidAmount(amount) {
       // var a = "^(?=.*[A-Za-z])(?=.*\d)(?=.*[$!%*#?&])[A-Za-z\d$!%*#?&]{8,}$";
        var a = "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!$%^&*-]).{8,14}$";

        if (amount.match(a)) {

        } else {

            $("#txtcontraseña").val("");
            $("#txtNcontraseña").val("");
            alert("La nueva contraseña debe contener mínimo 8 caracteres y máximo 14 una letra mayúscula, una letra minúscula, un número y un carácter especial (!#$%&/()=?¡/*)");
        }
    }
</script>
<style>
    #pnlcargararchivo {
        margin-top: 5%;
    }

    label.error {
        background-color: indianred;
        color: white;
        font-size: 13px;
        font-weight: bold;
        float: left;
        width: 100%;
        text-align: justify;
        font-weight: bold;
    }

    .Error {
        color: #800000;
        font-size: small;
        font-weight: bold;
    }

    .Tamaño {
        height: 200px;
    }

    .TamañoImag {
        height: 200px;
        position: center;
    }

    .TamañoDiv {
        position: page;
        /*width:1100px;*/
    }

    .btn-glyphicon {
        padding: 8px;
        background: #ffffff;
        margin-right: 4px;
    }

    .icon-btn {
        padding: 1px 15px 3px 2px;
        border-radius: 50px;
    }
</style>

AsaludEcopetrol/Views/Usuario/GestionInterna.cshtml
@{
    ViewBag.Title = "GestionInterna";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
}

<h2>GestionInterna</h2>

AsaludEcopetrol/Views/Usuario/Logout.cshtml
@{
    ViewBag.Title = "Logout";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
}

<h2>Logout</h2>

AsaludEcopetrol/Views/Usuario/LogoutSession.cshtml
@{
    ViewBag.Title = "LogoutSession";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
}