AsaludEcopetrol/Models/Evolucion/Cohorte.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AsaludEcopetrol.BussinesManager;
using ECOPETROL_COMMON.ENUM;
using ECOPETROL_COMMON.UTILOBJECTS;
using ECOPETROL_COMMON.ENTIDADES;
using static AsaludEcopetrol.Controllers.InicioSesion.UsuarioController;
using System.ComponentModel.DataAnnotations;

namespace AsaludEcopetrol.Models.Evolucion
{
    public class Cohorte
    {
        #region PROPIEDADES


        private Facede.Facade _BusClass;
        public Facede.Facade BusClass
        {
            get
            {
                if (_BusClass != null)
                {
                    return _BusClass;
                }
                else
                {
                    return _BusClass = new Facede.Facade();
                }

            }
            set { _BusClass = value; }
        }

        private BussinesManager.SessionState _SesionVar;
        public BussinesManager.SessionState SesionVar
        {
            get
            {
                if (_SesionVar == null)
                {
                    _SesionVar = new BussinesManager.SessionState();
                }
                return _SesionVar;
            }
            set { _SesionVar = value; }
        }

        private List<vw_ecop_concurrencia_cohorte> _LstCohorte;
        public List<vw_ecop_concurrencia_cohorte> LstCohorte
        {
            get
            {
                if (_LstCohorte == null)
                {
                    return _LstCohorte = new List<vw_ecop_concurrencia_cohorte>();
                }
                else
                {
                    return _LstCohorte;
                }

            }

            set
            {
                _LstCohorte = value;
            }
        }

        private List<Ref_ingreso_cohorte> _LstRefTipoCohorte;
        public List<Ref_ingreso_cohorte> LstRefTipoCohorte
        {
            get
            {
                if (_LstRefTipoCohorte == null)
                {
                    return _LstRefTipoCohorte = BusClass.GetRefTipoCohorte();
                }
                else
                {
                    return _LstRefTipoCohorte;
                }

            }

            set
            {
                _LstRefTipoCohorte = value;
            }
        }

        private ecop_concurrencia_cohorte _OBJCohorte;
        public ecop_concurrencia_cohorte OBJCohorte
        {
            get
            {
                if (_OBJCohorte == null)
                {
                    return _OBJCohorte = new ecop_concurrencia_cohorte();
                }
                else
                {
                    return _OBJCohorte;
                }

            }

            set
            {
                _OBJCohorte = value;
            }
        }


        MessageResponseOBJ MsgRes = new MessageResponseOBJ();


        #endregion


        public Int32 id_concurrencia { get; set; }


        [Required(ErrorMessage = "***")]
        [Display(Name = "INGRESO COHORTE")]
        public int id_ref_ingreso_cohorte { get; set; }

        [Required(ErrorMessage = "***")]
        [Display(Name = "OBSERVACIONES COHORTE")]
        public String Observacion { get; set; }

        #region METODOS     


        public void ConsultaCohorte(Int32 idConcu)
        {
            vw_ecop_concurrencia_cohorte objCC = new vw_ecop_concurrencia_cohorte();
            objCC.id_concurrencia = idConcu;
            LstCohorte = BusClass.ConsultaCohorte(objCC, ref MsgRes);
        }

        public void InsertarConcurrenciaCohorte(ref MessageResponseOBJ MsgRes)
        {
            BusClass.InsertarConcurrenciaCohorte(OBJCohorte, ref MsgRes);
        }

        #endregion



    }
}

AsaludEcopetrol/Controllers/Cohortes/CohortesController.cs
using AsaludEcopetrol.BussinesManager;
using ECOPETROL_COMMON.UTILOBJECTS;
using ECOPETROL_COMMON.ENTIDADES;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static AsaludEcopetrol.Controllers.InicioSesion.UsuarioController;
using LinqToExcel;
using System.Data;
using System.Configuration;
using System.Text;
using Aspose.Cells;
using System.Net;
using AsaludEcopetrol.Models;
using static AsaludEcopetrol.Models.Cohortes.Cohortes;
using ECOPETROL_COMMON.ENUM;
using OfficeOpenXml;
using System.Drawing;
using OfficeOpenXml.Style;
using System.Globalization;

namespace AsaludEcopetrol.Controllers.Cohortes
{
    [SessionExpireFilter]
    public class CohortesController : Controller
    {
        readonly Models.Cohortes.Cohortes Model = new Models.Cohortes.Cohortes();

        #region PROPIEDADES

        private SessionState _SesionVar;
        public SessionState SesionVar
        {
            get
            {
                if (_SesionVar == null)
                {
                    _SesionVar = new SessionState();
                }
                return _SesionVar;
            }
            set { _SesionVar = value; }
        }

        private Facede.Facade _BusClass;
        public Facede.Facade BusClass
        {
            get
            {
                if (_BusClass != null)
                {
                    return _BusClass;
                }
                else
                {
                    return _BusClass = new Facede.Facade();
                }

            }
            set { _BusClass = value; }
        }

        MessageResponseOBJ MsgRes = new MessageResponseOBJ();
        #endregion

        public ActionResult CargueCohortes()
        {
            ViewData["Alerta"] = "";
            ViewData["tipoalerta"] = 0;
            ViewBag.listaRegionales = BusClass.GetRefRegion();
            ViewBag.refcohortes = Model.Get_refCohortesSindh();
            return View();
        }

        [HttpPost]
        public ActionResult CargueCohortes(DateTime FechaCohorte, int tipocohorte, HttpPostedFileBase Archivo)
        {
            var ruta = "";
            var cohorte = Model.Get_refCohortes().Where(l => l.id_ref_cohortes == tipocohorte).FirstOrDefault();
            try
            {
                if (Archivo != null)
                {
                    ruta = DevolverRutaArchivo(Archivo);
                    var nombreArchivo = Archivo.FileName;

                    if (!nombreArchivo.Contains("cohorte"))
                    {
                        throw new Exception("Asegurese de que el archivo es el correcto. Este archivo no tiene en su nombre 'cohorte'");
                    }

                    string dirpath = Path.Combine(ruta);
                    WebClient User = new WebClient();
                    ruta = dirpath;
                    string filename = ruta;

                    var tipoArchivo = Path.GetExtension(Archivo.FileName);

                    Byte[] FileBuffer = User.DownloadData(filename);

                    byte[] array = new byte[0];
                    array = FileBuffer;
                    array = array.ToArray();

                    HttpPostedFileBase sigFile = (HttpPostedFileBase)new HttpPostedFileBaseCustom(array, Archivo.ContentType, Archivo.FileName + "." + tipoArchivo);

                    CellsHelper.CustomImplementationFactory = new MemoryStreamMemoryManager();
                    var asposeOptions = new Aspose.Cells.LoadOptions
                    {
                        MemorySetting = MemorySetting.MemoryPreference
                    };

                    Workbook wb = new Workbook(sigFile.InputStream, asposeOptions);
                    Worksheet worksheet = wb.Worksheets[0];
                    Cells cells = worksheet.Cells;
                    int MaximaFila = cells.MaxDataRow;

                    var ExportTableOptions = new Aspose.Cells.ExportTableOptions
                    {
                        CheckMixedValueType = false,
                        ExportColumnName = true,
                        ExportAsString = true
                    };

                    DataTable dataTable = worksheet.Cells.ExportDataTable(cells.MinRow, cells.MinColumn, cells.Rows.Count, cells.MaxColumn + 1, ExportTableOptions);

                    cohortes_cargue_base cargue = new cohortes_cargue_base();
                    cargue.fecha_cohorte = FechaCohorte;
                    cargue.id_ref_cohortes = tipocohorte;
                    cargue.fecha_digita = DateTime.Now;
                    cargue.usuario_digita = SesionVar.UserName;

                    var insercion = CargueMasivoDatos(dataTable, cargue, ref MsgRes);

                    var mensaje = "";

                    if (MsgRes.ResponseType == ECOPETROL_COMMON.ENUM.BussinesEnums.EnumTipoRespuesta.Correcto)
                    {
                        ViewData["Alerta"] = "El cargue de registros de la cohorte ha sido exitoso! ";
                        ViewData["tipoalerta"] = 1;
                        mensaje = "Correcto";
                    }
                    else
                    {
                        ViewData["Alerta"] = "Ha ocurrido un error en el cargue de la cohorte. Mensaje de error: " + MsgRes.DescriptionResponse;
                        ViewData["tipoalerta"] = 2;
                        mensaje = "Error de cargue";
                    }




                    //if (tipocohorte == 1)
                    //{
                    //    List<cohortes_detalle_cargue_OK> resultadosExcel = EntidadEpoc(path);
                    //    if (resultadosExcel.Count() > 0)
                    //    {

                    //        Model.InsertCohortesEPOC(cargue, resultadosExcel, ref MsgRes);
                    //        if (MsgRes.ResponseType == ECOPETROL_COMMON.ENUM.BussinesEnums.EnumTipoRespuesta.Correcto)
                    //        {
                    //            ViewData["Alerta"] = "El cargue de registros de la cohorte ha sido exitoso! ";
                    //            ViewData["tipoalerta"] = 1;
                    //        }
                    //        else
                    //        {
                    //            ViewData["Alerta"] = "Ha ocurrido un error en el cargue de la cohorte. Mensaje de error: " + MsgRes.DescriptionResponse;
                    //            ViewData["tipoalerta"] = 2;
                    //        }
                    //    }
                    //}
                    //else if (tipocohorte == 2 || cohorte.descripcion.Contains("PAD"))
                    //{
                    //    List<cohortes_detalle_cargue_OK> resultadosExcel = EntidadPad(path);
                    //    if (resultadosExcel.Count() > 0)
                    //    {
                    //        cohortes_cargue_base cargue = new cohortes_cargue_base();
                    //        cargue.fecha_cohorte = FechaCohorte;
                    //        cargue.id_ref_cohortes = tipocohorte;
                    //        cargue.fecha_digita = DateTime.Now;
                    //        cargue.usuario_digita = SesionVar.UserName;
                    //        Model.InsertCohortesPAD(cargue, resultadosExcel, ref MsgRes);
                    //        if (MsgRes.ResponseType == ECOPETROL_COMMON.ENUM.BussinesEnums.EnumTipoRespuesta.Correcto)
                    //        {
                    //            ViewData["Alerta"] = "El cargue de registros de la cohorte ha sido exitoso! ";
                    //            ViewData["tipoalerta"] = 1;
                    //        }
                    //        else
                    //        {
                    //            ViewData["Alerta"] = "Ha ocurrido un error en el cargue de la cohorte. Mensaje de error: " + MsgRes.DescriptionResponse;
                    //            ViewData["tipoalerta"] = 2;
                    //        }
                    //    }
                    //}
                    //else if (tipocohorte == 3 || cohorte.descripcion.Contains("RCV"))
                    //{
                    //    List<cohortes_detalle_cargue_OK> resultadosExcel = EntidadRCV(path);
                    //    if (resultadosExcel.Count() > 0)
                    //    {
                    //        cohortes_cargue_base cargue = new cohortes_cargue_base();
                    //        cargue.fecha_cohorte = FechaCohorte;
                    //        cargue.id_ref_cohortes = tipocohorte;
                    //        cargue.fecha_digita = DateTime.Now;
                    //        cargue.usuario_digita = SesionVar.UserName;
                    //        Model.InsertCohortesRCV(cargue, resultadosExcel, ref MsgRes);
                    //        if (MsgRes.ResponseType == ECOPETROL_COMMON.ENUM.BussinesEnums.EnumTipoRespuesta.Correcto)
                    //        {
                    //            ViewData["Alerta"] = "El cargue de registros de la cohorte ha sido exitoso! ";
                    //            ViewData["tipoalerta"] = 1;
                    //        }
                    //        else
                    //        {
                    //            ViewData["Alerta"] = "Ha ocurrido un error en el cargue de la cohorte. Mensaje de error: " + MsgRes.DescriptionResponse;
                    //            ViewData["tipoalerta"] = 2;
                    //        }
                    //    }
                    //}
                    //else
                    //{
                    //    List<cohortes_detalle_cargue_OK> resultadosExcel = EntidadGestantes(path);
                    //    if (resultadosExcel.Count() > 0)
                    //    {
                    //        cohortes_cargue_base cargue = new cohortes_cargue_base();
                    //        cargue.fecha_cohorte = FechaCohorte;
                    //        cargue.id_ref_cohortes = tipocohorte;

AsaludEcopetrol/Controllers/Evolucion/CohorteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AsaludEcopetrol.BussinesManager;
using ECOPETROL_COMMON.ENUM;
using ECOPETROL_COMMON.UTILOBJECTS;
using ECOPETROL_COMMON.ENTIDADES;
using static AsaludEcopetrol.Controllers.InicioSesion.UsuarioController;

namespace AsaludEcopetrol.Controllers.Evolucion
{
    [SessionExpireFilter]

    public class CohorteController : Controller
    {
        #region  PROPIEDADES

        private SessionState _SesionVar;
        public SessionState SesionVar
        {
            get
            {
                if (_SesionVar == null)
                {
                    _SesionVar = new SessionState();
                }
                return _SesionVar;
            }
            set { _SesionVar = value; }
        }

        MessageResponseOBJ MsgRes = new MessageResponseOBJ();

        #endregion



        // GET: Cohorte
        public ActionResult ConcurrenciaCohorte(String idConcu)
        {
            Models.Evolucion.Cohorte Model = new Models.Evolucion.Cohorte();
            if (!(String.IsNullOrEmpty(idConcu)))
            {
                Model.id_concurrencia = (Convert.ToInt32(idConcu));
                Model.ConsultaCohorte(Convert.ToInt32(idConcu));


                return View(Model);
            }
            else
            {
                return RedirectToAction("Inicio", "Usuario");

            }

        }

        [HttpPost]
        public ActionResult ConcurrenciaCohorte(Models.Evolucion.Cohorte Model)
        {

            Model.OBJCohorte.id_concurrencia = Model.id_concurrencia;
            Model.OBJCohorte.id_ref_ingreso_cohorte = Model.id_ref_ingreso_cohorte;
            Model.OBJCohorte.observacion = Model.Observacion;
            Model.OBJCohorte.usuario_digita = SesionVar.UserName;
            Model.OBJCohorte.fecha_digita = DateTime.Now;

            Model.InsertarConcurrenciaCohorte(ref MsgRes);

            if (MsgRes.ResponseType == BussinesEnums.EnumTipoRespuesta.Correcto)
            {
                return RedirectToAction("ConcurrenciaCohorte", "Cohorte", new { idConcu = Model.id_concurrencia });
            }
            else
            {
                ModelState.AddModelError("", "ERROR... ACTUALIZANDO....");
            }


            return View(Model);
           
          

        }


    }
}

AsaludEcopetrol/Views/Cohortes/CargueDatosGRPC.cshtml
@{
    ViewBag.Title = "CARGUE MASIVO GRPC";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
    string alerta = (string)ViewData["alerta"];

}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="text-primary_asalud">CARGUE DATOS</strong>
        </div>
        <div class="panel-body">
            <form id="formulario">
                <div class="row">
                    <div class="col-sm-3">
                        <label class="text-secondary_asalud">Archivo</label>
                        <input type="file" name="file" id="file" class="form-control" required multiple />
                    </div>
                    <div class="col-sm-3 form-group">
                        <label class="text-secondary_asalud">Tipo:</label>
                        <select class="form-control select2" id="id_tipo" name="id_tipo" required>
                            <option value="">- Seleccionar -</option>
                            @foreach (ECOPETROL_COMMON.ENTIDADES.ref_cargue_vigilanciaCohortes_tipos item in ViewBag.tipo)
                            {
                                <option value="@item.id_tipo">@item.descripcion</option>
                            }
                        </select>
                    </div>
                    <div class="col-sm-3 form-group">
                        <label class="text-secondary_asalud">Mes:</label>
                        <select class="form-control select2" id="mes" name="mes" required>
                            <option value="">- Seleccionar -</option>
                            @foreach (ECOPETROL_COMMON.ENTIDADES.ref_meses_del_año item in ViewBag.mes)
                            {
                                <option value="@item.id_mes">@item.descripcion</option>
                            }
                        </select>
                    </div>
                    <div class="col-sm-3 form-group">
                        <label class="text-secondary_asalud">Año:</label>
                        <input autocomplete="off" type="text" class="form-control solo-numero solo-numero2 solo-numero3 year" id="año" name="año" maxlength="4" required />
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-sm-12">
                        <label style="visibility:hidden;width:100%" class="text-secondary_asalud">boton</label>
                        <button class="button_Asalud_Guardar" type="button" onclick="ValidarFormulario()">Cargar registros</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="~/Scripts/validate.js"></script>


<script>

    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
    var lecturaArchivo = [];

    $(document).ready(function () {
        $('.select2').select2({
            width: '100%',
            height: '100%'
        });

        $('.solo-numero').keyup(function () {
            this.value = (this.value + '').replace(/[^0-9]/g, '');
        });

        $(".k-input").attr('readonly', true);
    });

    $("#file").change(function () {
        var data = document.getElementById('file');
        var distintosArchivos = data.files;
        var contador = 0;

        if (distintosArchivos.length < 30) {

            for (contador; contador < distintosArchivos.length; contador++) {

                var nameext = data.files[contador].name;
                var extension = getFileExtension3(nameext);

                var listaextensiones = ["xlsx", "xlsm", "xlsb", "xltx", "xltm", "xls"];

                var valida = false;

                jQuery.each(listaextensiones, function (i, val) {
                    if (extension == val) {
                        valida = true;
                    }
                });

                if (valida == false) {
                    alert("La extensión " + extension + " no es válida. Por favor, solo subir archivos EXCEL.");
                    $("#file").val("");
                }
            }
        }
        else {
            alert("Solo se pueden subir 30 archivos.");
            $("#file").val("");
            return false;
        }
    });

    function getFileExtension3(filename) {
        return filename.slice((filename.lastIndexOf(".") - 1 >>> 0) + 2);
    }

    function ValidarFormulario() {
        var validator = $("#formulario").validate();
        if (validator.form()) {
            GuardarDatos();
        }
    }

    function GuardarDatos() {
        var formData = new FormData($("form")[0]);
        formData.append("archivo", $("input[type=file]")[0].files[0]);
        formData.append("mes", $("#mes").val());
        formData.append("año", $("#año").val());
        formData.append("tipo", $("#id_tipo").val());

        LoadingShow();
        $.ajax({
            url: "@Url.Action("GuardarDatosMasivos", "Cohortes")",
            type: "post",
            data: formData,
            method: 'POST',
            contentType: false,
            processData: false,

            success: function (data) {

                alert(data.mensaje);
                LoadingHide();

                if (data.rta == 1) {
                    location.reload();
                }
            }
        })
    }

</script>

AsaludEcopetrol/Views/Cohortes/ModalGestionGRCP.cshtml
@model ECOPETROL_COMMON.ENTIDADES.management_VigilanciaCohortes_detalleParaGestionarResult

<div class="panel panel-default">
    <div class="panel-body">
        <div class="panel-body table-responsive">
            <table class="table table-bordered table-responsive" style="width:98%;">
                <tbody>
                    <tr>
                        <th>Lote</th>
                        <th>Registro</th>
                        <th>Documento paciente</th>
                        <th>Nombre paciente</th>
                        <th>IPS</th>
                        <th>Diagnóstico</th>
                    </tr>
                </tbody>
                <tr>
                    <td>@Model.id_lote</td>
                    <td>@Model.id_registro</td>
                    <td>@Model.documento_paciente</td>
                    <td>@Model.nombre_paciente</td>
                    <td>@Model.nombre_prestador</td>
                    <td>@Model.codigo_dx_detectado - @Model.descripcion_dx_detectado</td>
                </tr>
            </table>
        </div>
    </div>
</div>
<br />

<form id="formGestion">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <input type="hidden" id="idLote" name="idLote" value="@ViewBag.idLote" />
                    <input type="hidden" id="idRegistro" name="idRegistro" value="@ViewBag.idRegistro" />

                    <label class="text-secondary_asalud">Gestión</label>
                    <select id="gestion" name="gestion" class="form-control" required onchange="gestionHecha(this.value)">
                        <option value="">-Seleccione-</option>
                        <option value="Confirmado">Confirmado</option>
                        <option value="Descartado">Decartado</option>
                    </select>
                </div>
            </div>
            <br />

            <div class="row" id="divConfirmado" style="display:none">
                <div class="col-md-6">
                    <label class="text-secondary_asalud">Fecha confirmación</label>
                    <input type="text" class="form-control datepickerr" id="fecha_confirmacion" name="fecha_confirmacion" style="width:100%;" required />
                </div>
                <br />

                <div class="col-md-12">
                    <label class="text-secondary_asalud">Justificación confirmación</label>
                    <textarea id="observacion_confirmacion" name="observacion_confirmacion" class="form-control char-count" cols="4" rows="5" maxlength="2000" required></textarea>
                    <p class="charCount">Te quedan 2000 caracteres.</p>
                </div>
            </div>

            <div class="row" id="divDescartado" style="display:none">
                <div class="col-md-12">
                    <label class="text-secondary_asalud">Observación descarte</label>
                    <textarea id="observacion_descarte" name="observacion_descarte" class="form-control char-count" cols="4" rows="5" maxlength="2000"></textarea>
                    <p class="charCount">Te quedan 2000 caracteres.</p>
                </div>
            </div>

            <br />
            <div class="row" style="text-align:center;">
                <a class="button_Asalud_Guardar" onclick="GuardarGestion()">Guardar</a>
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {

        $('.select3').select2({
            width: '100%'
        });

        $(".datepickerr").kendoDatePicker({
            format: "MM/dd/yyyy",
            max: new Date(),
        });

        $(".k-input").attr('readonly', true);


        $('.char-count').each(function () {
            var maxLength = $(this).attr('maxlength'); // Obtiene el maxlength de cada textarea
            var $counter = $(this).next('.charCount'); // Obtiene el elemento <p> siguiente para mostrar el conteo

            // Inicializa el contador con el máximo de caracteres
            $counter.text('Te quedan ' + maxLength + ' caracteres.');

            // Actualiza el contador al escribir en el textarea
            $(this).on('input', function () {
                var textLength = $(this).val().length;
                var charsRemaining = maxLength - textLength;
                $counter.text('Te quedan ' + charsRemaining + ' caracteres.');
            });
        });
    });


    function gestionHecha(valor) {
        if (valor == "Confirmado") {
            document.getElementById("divConfirmado").style.display = "block";
            document.getElementById("divDescartado").style.display = "none";
        } else {
            document.getElementById("divConfirmado").style.display = "none";
            document.getElementById("divDescartado").style.display = "block";
        }
    }

    function GuardarGestion() {
        var valida = $("#formGestion").validate();
        if (valida.form()) {
            EnviarDatos();
        }
    }

    function EnviarDatos() {

        var formData = new FormData($("#formGestion")[0]);
        formData.append("idLote", $("#idLote").val());
        formData.append("idRegistro", $("#idRegistro").val());
        formData.append("gestion", $("#gestion").val());
        formData.append("fecha_confirmacion", $("#fecha_confirmacion").val());
        formData.append("observacion_confirmacion", $("#observacion_confirmacion").val());
        formData.append("observacion_descarte", $("#observacion_descarte").val());

        LoadingShow();

            $.ajax({
                url: '@Url.Action("GuardarGestion", "Cohortes")',
                type: "POST",
                data: formData,
                method: "POST",
                processData: false,
                contentType: false,

                success: function (response) {
                    alert(response.mensaje);
                    LoadingHide();
                    if (response.rta == 1) {
                        location.reload();
                    }
                },
                error: function (xhr, status, error) {
                    LoadingHide();
                }
            });

    }


</script>
<style>
    .charCount {
        font-size: 10px;
    }
</style>

AsaludEcopetrol/Views/Cohortes/ModalGestionRealizada.cshtml
@model ECOPETROL_COMMON.ENTIDADES.management_VigilanciaCohortes_gestionesResult

<form id="formGestion">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="panel-body table-responsive">
                <table class="table table-bordered table-responsive" style="width:98%;">
                    <tbody>
                        <tr>
                            <th>Gestión</th>
                            <th>Lote</th>
                            <th>Gestión</th>
                            @if (Model.gestion != null)
                            {
                                if (Model.gestion == "Confirmado")
                                {
                                    <th>Fecha confirmación</th>
                                    <th>Justificación confirmación</th>
                                }
                                else
                                {
                                    <th>Fecha descarte</th>
                                    <th>Observación descarte</th>
                                }
                            }
                            else
                            {
                                <th></th>
                                <th></th>
                            }

                            <th>Fecha gestión</th>
                            <th>Usuario gestiona</th>
                        </tr>
                    </tbody>
                    <tr>
                        <td>@Model.id_gestion</td>
                        <td>@Model.id_lote</td>
                        <td>@Model.gestion</td>

                        @if (Model.gestion != null)
                        {
                            if (Model.gestion == "Confirmado")
                            {
                                <td>@Model.fecha_confirmacion.Value.ToString("dd/MM/yyyy")</td>
                                <td>@Model.observacion_confirmacion</td>
                            }
                            else
                            {
                                <td>@Model.fecha_descarte.Value.ToString("dd/MM/yyyy")</td>
                                <td>@Model.observacion_descarte</td>
                            }
                        }
                        else
                        {
                            <td></td>
                            <td></td>
                        }

                        <td>@Model.fecha_digita.Value.ToString("dd/MM/yyyy")</td>
                        <td>@Model.nombreDigita</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</form>