AsaludEcopetrol/Controllers/Facturacion/FacturacionSapController.cs
using AsaludEcopetrol.BussinesManager;
using ECOPETROL_COMMON.UTILOBJECTS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using ECOPETROL_COMMON.ENTIDADES;
using LinqToExcel;
using System.Data.OleDb;
using System.Data;
using OfficeOpenXml;
using System.Drawing;
using OfficeOpenXml.Style;
using System.Globalization;
using ClosedXML.Excel;

namespace AsaludEcopetrol.Controllers.Facturacion
{
    public class FacturacionSapController : Controller
    {
        #region  PROPIEDADES

        private SessionState _SesionVar;
        public SessionState SesionVar
        {
            get
            {
                if (_SesionVar == null)
                {
                    _SesionVar = new SessionState();
                }
                return _SesionVar;
            }
            set { _SesionVar = value; }
        }

        private Facede.Facade _BusClass;
        public Facede.Facade BusClass
        {
            get
            {
                if (_BusClass != null)
                {
                    return _BusClass;
                }
                else
                {
                    return _BusClass = new Facede.Facade();
                }

            }
            set { _BusClass = value; }
        }

        MessageResponseOBJ MsgRes = new MessageResponseOBJ();

        #endregion
        public ActionResult CargueFacturacionSap(int? rta, string msg)
        {
            Models.Facturacion.FacturacionSap Model = new Models.Facturacion.FacturacionSap();

            Models.General General = new Models.General();

            if (rta == 1)
            {
                ViewData["msg"] = msg;
            }
            else if (rta == 2)
            {
                ViewData["msg"] = msg;
            }
            else
            {
                ViewData["msg"] = "";
            }

            ViewData["rta"] = 0;

            if (rta != 0 && rta != null)
            {
                ViewData["rta"] = rta;
            }

            return View(Model);
        }

        public JsonResult GuardarFacturacionSap(HttpPostedFileBase file)
        {
            Models.Facturacion.FacturacionSap Model = new Models.Facturacion.FacturacionSap();

            var rta = 0;
            var resultado = false;
            var mensaje = "";

            try
            {

                using (var workbook = new XLWorkbook(file.InputStream))
                {
                    var worksheet = workbook.Worksheet(1); // Asume que el archivo tiene al menos una hoja
                    var range = worksheet.RangeUsed(); // Obtiene el rango de celdas con datos

                    // Convertir el rango a DataTable
                    DataTable dataTable = new DataTable();
                    bool firstRow = true;

                    foreach (var row in range.Rows())
                    {
                        if (firstRow)
                        {
                            // Crear columnas a partir de la primera fila
                            foreach (var cell in row.Cells())
                            {
                                dataTable.Columns.Add(cell.GetValue<string>());
                            }
                            firstRow = false;
                        }
                        else
                        {
                            // Agregar filas al DataTable
                            var newRow = dataTable.NewRow();
                            for (int i = 0; i < row.Cells().Count(); i++)
                            {
                                newRow[i] = row.Cell(i + 1).GetValue<string>();
                            }
                            dataTable.Rows.Add(newRow);
                        }
                    }

                    facturacion_sap_cargue obj = new facturacion_sap_cargue();
                    obj.fecha_digita = DateTime.Now;
                    obj.usuario_digita = SesionVar.UserName;

                    List<facturacion_sap_dtll> list = Model.ValidacionArchivo(dataTable, ref MsgRes);

                    if (MsgRes.ResponseType == ECOPETROL_COMMON.ENUM.BussinesEnums.EnumTipoRespuesta.Correcto)
                    {
                        Model.InsertarFacturacionSAP(list, obj, ref MsgRes);

                        if (MsgRes.ResponseType == ECOPETROL_COMMON.ENUM.BussinesEnums.EnumTipoRespuesta.Correcto)
                        {
                            rta = 1;
                            mensaje = "INGRESO DE FACTURACIÓN SAP CARGADO CORRECTAMENTE";
                            resultado = true;
                        }
                        else
                        {
                            rta = 2;
                            mensaje = MsgRes.DescriptionResponse;
                        }
                    }
                    else
                    {
                        rta = 2;
                        mensaje = MsgRes.DescriptionResponse;
                    }
                }
            }
            catch (Exception ex)
            {
                rta = 2;
                mensaje = MsgRes.DescriptionResponse + ex.Message;
            }

            return Json(new { success = resultado, rta = rta, msg = mensaje }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult TableroFacturacionSAP(DateTime? fechaIni, DateTime? fechaFin)
        {
            List<management_facturacionSAP_listaResult> list = new List<management_facturacionSAP_listaResult>();
            management_facturacionSAP_listaResult consolidado = new management_facturacionSAP_listaResult();

            var opera = 0;

            if (fechaIni != null || fechaFin != null)
            {
                list = BusClass.ListarFacturacionSAP();
                opera = 1;
            }

            ViewBag.conteo = 0;
            ViewBag.resultado = 0;

            if (fechaIni != null)
            {
                list = list.Where(x => x.fecha_digita >= fechaIni).ToList();
            }

            if (fechaFin != null)
            {
                list = list.Where(x => x.fecha_digita <= fechaFin).ToList();
            }

            if (list.Count() > 0)
            {
                consolidado = list.FirstOrDefault();
                ViewBag.conteo = list.Sum(x => x.conteo);
                //ViewBag.conteo = consolidado.conteo;

                if (opera == 1)
                {
                    ViewBag.resultado = 1;
                }
            }
            else
            {
                if (opera == 1)
                {
                    ViewBag.resultado = 2;
                }
            }

            ViewBag.list = list;
            Session["Ini"] = fechaIni;
            Session["Fin"] = fechaFin;

            return View();

        }

        public string DevolverMes(int mes)
        {
            var Devueltames = "";

            if (mes == 1)
            {
                Devueltames = "Enero";
            }
            else if (mes == 2)
            {
                Devueltames = "Febrero";
            }
            else if (mes == 3)
            {
                Devueltames = "Marzo";
            }
            else if (mes == 4)
            {
                Devueltames = "Abril";
            }
            else if (mes == 5)
            {
                Devueltames = "Mayo";
            }
            else if (mes == 6)
            {
                Devueltames = "Junio";
            }
            else if (mes == 7)
            {
                Devueltames = "Julio";
            }
            else if (mes == 8)
            {
                Devueltames = "Agosto";
            }
            else if (mes == 9)
            {
                Devueltames = "Septiembre";
            }
            else if (mes == 10)
            {
                Devueltames = "Octubre";
            }
            else if (mes == 11)
            {
                Devueltames = "Noviembre";
            }
            else if (mes == 12)
            {
                Devueltames = "Diciembre";
            }
            return Devueltames;
        }

        public void DescargarDatosFacturacion()
        {
            DateTime fechaIni = (DateTime)Session["Ini"];
            DateTime fechaFin = (DateTime)Session["Fin"];

            List<management_facturacionSAP_listaREPORTEResult> list = new List<management_facturacionSAP_listaREPORTEResult>();
            list = BusClass.ListarFacturacionSAPReporte(fechaIni, fechaFin).ToList();

            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Descargue");

            Sheet.Cells["A1:W1"].Style.Font.Bold = true;
            Color colFromHex = Color.FromArgb(22, 54, 92);
            Sheet.Cells["A1:W1"].Style.Fill.PatternType = ExcelFillStyle.Solid;
            Sheet.Cells["A1:W1"].Style.Fill.BackgroundColor.SetColor(colFromHex);
            Sheet.Cells["A1:W1"].Style.Font.Color.SetColor(Color.White);
            Sheet.Cells["A1:W1"].Style.Font.Name = "Century Gothic";

            Sheet.Cells["A1"].Value = "Sociedad";
            Sheet.Cells["B1"].Value = "Cuenta";
            Sheet.Cells["C1"].Value = "NIT";
            Sheet.Cells["D1"].Value = "Cuenta de mayor";
            Sheet.Cells["E1"].Value = "Nº documento";
            Sheet.Cells["F1"].Value = "Clase de documento";
            Sheet.Cells["G1"].Value = "Referencia";
            Sheet.Cells["H1"].Value = "Referencia sin letras";
            Sheet.Cells["I1"].Value = "Fe.contabilización";
            Sheet.Cells["J1"].Value = "Fecha compensación";
            Sheet.Cells["K1"].Value = "Fecha de pago";

            Sheet.Cells["L1"].Value = "Moneda del documento";
            Sheet.Cells["M1"].Value = "Importe en moneda doc.";
            Sheet.Cells["N1"].Value = "Nombre del usuario";
            Sheet.Cells["O1"].Value = "Texto";

AsaludEcopetrol/Views/FacturacionSap/CargueFacturacionSap.cshtml
@{
    ViewBag.Title = "CARGUE MASIVO FACTURACIÓN SAP";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
    string msg = (string)ViewData["Msg"];
    int rta = (int)ViewData["rta"];
}

<br />


<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="text-primary_asalud">CARGUE DATOS</strong>
        </div>
        <div class="panel-body">
            @if (rta > 0)
            {
                <div class="form-group">
                    @if (rta == 1)
                    {
                        <div class="alert alert-success">
                            <strong>Éxito!</strong> @msg
                        </div>
                    }
                    else
                    {
                        <div class="alert alert-danger">
                            <strong>Error!</strong> @msg
                        </div>
                    }
                </div>
                <br />
            }
            <form id="formulario" name="formulario" action="GuardarFacturacionSap" method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-sm-4">
                        <label class="text-secondary_asalud">Archivo</label>
                        <input type="file" class="form-control" id="file" name="file" required />
                    </div>

                    <div class="col-sm-12 text-center">
                        <div class="col-sm-12 text-right">
                            <button class="button_Asalud_Guardar" type="button" onclick="ValidarFormulario()">Cargar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/Scripts/validate.js"></script>
<script>

    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }

    $(document).ready(function () {

        $('.select2').select2({
            width: '100%',
            height: '100%'
        });

        $('.solo-numero').keyup(function () {
            this.value = (this.value + '').replace(/[^0-9]/g, '');
        });

    });

    $("#file").change(function () {

        var data = document.getElementById('file');
        var nameext = data.files[0].name;
        var extension = getFileExtension3(nameext);

        var listaextensiones = ["XLSX", "XLS" , "XLSB" , "xlsx", "xlsm", "xlsb", "xltx", "xltm", "xls"];

        var valida = false;

        jQuery.each(listaextensiones, function (i, val) {
            if (extension == val) {
                valida = true;
            }
        });

        if (valida == false) {
            alert("La extension no es valida");
            $("#file").val("");
        }

    });

    function getFileExtension3(filename) {
        return filename.slice((filename.lastIndexOf(".") - 1 >>> 0) + 2);
    }

      function ValidarFormulario() {
        var validator = $("#formulario").validate();
        if (validator.form()) {

            GuardarDatos();
        }
    }

    debugger
    function GuardarDatos() {

        var formData = new FormData($("form")[0]);

        formData.append("file", $("input[type=file]")[0].files[0]);

        var rta = 0;
        var msg = "";

        LoadingShow();
        $.ajax({
            url: "@Url.Action("GuardarFacturacionSap", "FacturacionSap")",
            type: "post",
            data: formData,
            method: 'POST',
            contentType: false,
            processData: false,

            success: function (response) {

                rta = response.rta;
                msg = response.msg;

                if (response.success) {

                    LoadingHide();
                    window.location.href = "@Url.Action("CargueFacturacionSap")?rta=" + rta + "&msg=" + msg;

                }
                else {

                    LoadingHide();
                    window.location.href = "@Url.Action("CargueFacturacionSap")?rta=" + rta + "&msg=" + msg;
                }

            }
        })
    }

</script>


<style>

    .control-label {
        font-size: 15px;
        color: #357ebd;
    }

    .letra {
        font-size: 15px
    }

    .error {
        color: indianred;
        font-size: 13px;
    }

    .control-label {
        font-size: 15px;
    }

    .alert-new {
        color: #012f51;
        background-color: #dcdcdc;
        border-color: #8c8c8c;
        margin-right: 1%;
    }

    .contentErr {
        width: 50%;
        background: white;
        position: fixed;
        top: 20%;
        left: 25%;
        padding: 15px;
    }

    .showErroneos {
        background: rgba(0,0,0,0.4);
        width: 100%;
        height: 100%;
        position: fixed;
        top: 0px;
        left: 0px;
        z-index: 2;
    }

    .cortinilla {
        background: rgba(0,0,0,0.2);
        width: 100%;
        height: 100%;
        position: fixed;
        top: 0px;
        left: 0px;
        z-index: 2;
    }

    .ventana {
        width: 15%;
        height: 25%;
        padding: 1%;
        background-image: url(../../Resources/cargando.gif);
        background-size: 100% 100%;
        top: 40%;
        left: 42.5%;
        position: relative;
    }

    .k-autocomplete.k-header {
        width: 300px;
    }

    .Acordion {
        width: 820px;
    }

    .AcordionVentana {
        width: 100px;
        height: 100px;
    }

    .Error {
        color: #800000;
        font-size: small;
        font-weight: bold;
    }

    .Info {
        color: #800000;
        font-size: small;
        text-align: justify;
        font-weight: bold;
        width: 700px;
    }

    .Enca {
        width: 700px;
        text-align: center;
        background-color: #284775;
        color: #ffffff;
    }

    .ListCaja {
        width: 50%;
        border-collapse: collapse;
    }

    .th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    .td {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }

    .General {
        font-size: x-small;
        font-family: Calibri;
    }

    .TamañoImag {
        height: 200px;
        position: center;
    }

    .TamañoDiv {
        position: page;
        /*width:1100px;*/
    }

    .btn-glyphicon {
        padding: 8px;
        background: #ffffff;
        margin-right: 4px;
    }

    .icon-btn {
        padding: 1px 15px 3px 2px;
        border-radius: 50px;
    }
</style>

AsaludEcopetrol/Views/FacturacionSap/TableroFacturacionSAP.cshtml
@{
    ViewBag.Title = "TABLERO FACTURAS SAP";
    Layout = "~/Views/Shared/_LayoutECOPETROL.cshtml";
    int conteoResultados = ViewBag.conteo;
    int resultado = ViewBag.resultado;
}

<br />

<div class="panel panel-default">
    <div class="panel-heading">
        <strong class="text-primary-Asalud">FACTURACIÓN SAP</strong>
    </div>
    <div class="panel-body">
        <form id="formulario" action="TableroFacturacionSAP" method="post">
            <div class="row">
                <div class="col-sm-3 form-group">
                    <label class="text-secondary_asalud">Fecha inicio</label>
                    <input class="datepickerr" style="width: 100%" name="fechaIni" id="fechaIni" required />
                </div>
                <div class="col-sm-3 form-group">
                    <label class="text-secondary_asalud">Fecha final</label>
                    <input class="datepickerr" style="width: 100%" name="fechaFin" id="fechaFin" required />
                </div>
            </div>
            @if (resultado == 2)
            {
                <div class="row">
                    <div class="col-sm-12" style="text-align:center; font-family:'Century Gothic'; color:red;">
                        <p style="font-family:'Century Gothic'">@Html.Raw("No hay datos en el periodo filtrado")</p>
                    </div>
                </div>
            }
            @if (ViewBag.conteo != 0)
            {
                <div class="row">
                    <div class="col-sm-4 form-group">
                        <label class="text-secondary_asalud"> Total de registros: @conteoResultados</label>
                    </div>
                </div>
            }
            <div class="row">
                <div class="col-sm-12 form-group text-right">
                    <button class="btn button_Asalud_Guardar" type="button" onclick="ValidarFormulario()"><i class="glyphicon glyphicon-search"></i>&nbsp;Buscar</button>
                    @if (ViewBag.conteo != 0)
                    {
                        <a class="btn button_Asalud_descargas" href="@Url.Action("DescargarDatosFacturacion", "FacturacionSap")"><i class="glyphicon glyphicon-download"></i>&nbsp; Exportar reporte</a>

                    }
                </div>
            </div>
        </form>

        <br />
        <table id="tabla" class="table table-bordered">
            <thead>
                <tr>
                    <th>Ítem</th>
                    <th>Fecha cargue</th>
                    <th>Usuario cargue</th>
                    <th>Cargados</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int i = 0;
                }
                @foreach (var item in ViewBag.list)
                {
                    i++;
                    <tr>
                        <td class="text-center">@item.id_factura_cargue</td>
                        <td>@item.fecha_digita</td>
                        <td>@item.usuario_digita</td>
                        <td>@item.conteo</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script src="~/Scripts/validate.js"></script>
<script>

    $(document).ready(function () {
        $('.select2').select2({
            width: '100%'
        });

        $(".datepickerr").kendoDatePicker({
            format: "MM/dd/yyyy",
        });

        $('.solo-numero').keyup(function () {
            this.value = (this.value + '').replace(/[^0-9]/g, '');
        });

        $(".k-input").attr('readonly', true);

        //$('#FechaInicialfiltro').attr('disabled', 'disabled');
        //$('#FechaFinalfiltro').attr('disabled', 'disabled');
    })

    debugger
    function cerrarModal() {
        location.reload();

    }

    $('.table').DataTable({
        "sSearch": "Buscar:",
        "searching": true,
        "iDisplayLength": 15,
        "lengthChange": false,
        "info": false,
        responsive: true,
        language: {
            "decimal": "",
            "emptyTable": "No hay información",
            "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
            "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
            "infoFiltered": "(Filtrado de _MAX_ total entradas)",
            "infoPostFix": "",
            "thousands": ",",
            "lengthMenu": "Mostrar _MENU_ Entradas",
            "loadingRecords": "Cargando...",
            "processing": "Procesando...",
            "search": "Buscar:",
            "zeroRecords": "Sin resultados encontrados",
            "paginate": {
                "first": "Primero",
                "last": "Ultimo",
                "next": "Siguiente",
                "previous": "Anterior"
            }
        },
    });

    function ValidarFormulario() {
        var validator = $("#formulario").validate();
        if (validator.form) {
            $("#formulario").submit();
        }
    }

</script>


<style>


    .control-label {
        font-size: 15px;
        color: #357ebd;
    }

    .letra {
        font-size: 15px
    }

    .error {
        color: indianred;
        font-size: 13px;
    }

    .control-label {
        font-size: 15px;
    }

    #pnlcargararchivo {
        margin-top: 5%;
    }

    label.error {
        float: left;
    }

    .alert-new {
        color: #012f51;
        background-color: #dcdcdc;
        border-color: #8c8c8c;
        margin-right: 1%;
    }

    .contentErr {
        width: 50%;
        background: white;
        position: fixed;
        top: 20%;
        left: 25%;
        padding: 15px;
    }

    .showErroneos {
        background: rgba(0,0,0,0.4);
        width: 100%;
        height: 100%;
        position: fixed;
        top: 0px;
        left: 0px;
        z-index: 2;
    }

    .cortinilla {
        background: rgba(0,0,0,0.2);
        width: 100%;
        height: 100%;
        position: fixed;
        top: 0px;
        left: 0px;
        z-index: 2;
    }

    .ventana {
        width: 15%;
        height: 25%;
        padding: 1%;
        background-image: url(../../Resources/cargando.gif);
        background-size: 100% 100%;
        top: 40%;
        left: 42.5%;
        position: relative;
    }

    .k-autocomplete.k-header {
        width: 300px;
    }

    .Acordion {
        width: 820px;
    }

    .AcordionVentana {
        width: 100px;
        height: 100px;
    }

    .Error {
        color: #800000;
        font-size: small;
        font-weight: bold;
    }

    .Info {
        color: #800000;
        font-size: small;
        text-align: justify;
        font-weight: bold;
        width: 700px;
    }

    .Enca {
        width: 700px;
        text-align: center;
        background-color: #284775;
        color: #ffffff;
    }

    .ListCaja {
        width: 50%;
        border-collapse: collapse;
    }

    .th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    .td {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }

    .General {
        font-size: x-small;
        font-family: Calibri;
    }

    .Tamaño {
        height: 200px;
    }

    .TamañoImag {
        height: 200px;
        position: center;
    }

    .TamañoDiv {
        position: page;
    }

    .btn-glyphicon {
        padding: 8px;
        background: #ffffff;
        margin-right: 4px;
    }

    .icon-btn {
        padding: 1px 15px 3px 2px;
        border-radius: 50px;
    }

    .text-secondary_asalud {
        font-family: "Century Gothic", "Century Gothic", Sans-Serif;
        color: #556da2;
    }

    input:read-only {
        background-color: #636363;
        color: #357ebd;
    }

    #tabla {
        font-family: "Century Gothic", "Century Gothic", Sans-Serif;
        font-size: 12px;
        margin: 10px;
        width: 100%;
        text-align: left;
        border-collapse: collapse;
    }

        #tabla th {
            font-weight: bold;
            padding: 8px;
            background: #636363;
            border-top: 4px solid #aabcfe;
            border-bottom: 1px solid #fff;
            color: #e8e8e8;
        }

        #tabla td {
            padding: 8px;
            background: #efefef;
            border-bottom: 2px solid #fff;
            color: #636363;
            border-top: 1px solid transparent;
        }

        #tabla tr:hover td {
            background: #bcbcbc;
            color: #1c1c1c;
        }

    .floatBlock {
        margin: 0 1.81em 0 0;
    }
</style>

AsaludEcopetrol/Views/FacturacionSap/_TableroFacturacionSAPDetalle.cshtml
@{
    int conteoResultados = ViewBag.conteo;
}

<div class="panel panel-default">
    <div class="panel-heading">
        <strong class="text-primary-Asalud">DETALLE FACTURACIÓN SAP</strong>
    </div>
    <div class="panel-body">

        <table id="tabla2" class="table2 table-bordered table-responsive" style="font-size:10px; width: 100%;">
                <thead>
                    <tr>
                        <th>Ítem</th>
                        <th>Nit</th>
                        <th>Nro documento</th>
                        <th>Referencia</th>
                        <th>Fecha contabilización</th>
                        <th>Fecha compensanción</th>
                        <th>Fecha pago</th>
                        <th>Regional</th>
                        <th>Unis</th>
                        <th>Localidad</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int i = 0;
                    }
                    @foreach (var item in ViewBag.list)
                    {
                        i++;
                        <tr>
                            <td class="text-center">@item.id_factura_sap</td>
                            <td>@item.nit</td>
                            <td>@item.nro_documento</td>
                            <td>@item.referencia</td>
                            <td>@item.fe_contabilizacion</td>
                            <td>@item.fecha_compensacion</td>
                            <td>@item.fecha_pago</td>
                            <td>@item.regional</td>
                            <td>@item.unis</td>
                            <td>@item.localidad</td>
                        </tr>
                    }
                </tbody>
            </table>
</div>
</div>



<script>

    $('.table2').DataTable({
        "sSearch": "Buscar:",
        "searching": true,
        "iDisplayLength": 25,
        "lengthChange": false,
        "info": false,
        responsive: true,
        language: {
            "decimal": "",
            "emptyTable": "No hay información",
            "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
            "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
            "infoFiltered": "(Filtrado de _MAX_ total entradas)",
            "infoPostFix": "",
            "thousands": ",",
            "lengthMenu": "Mostrar _MENU_ Entradas",
            "loadingRecords": "Cargando...",
            "processing": "Procesando...",
            "search": "Buscar:",
            "zeroRecords": "Sin resultados encontrados",
            "paginate": {
                "first": "Primero",
                "last": "Ultimo",
                "next": "Siguiente",
                "previous": "Anterior"
            }
        },
    });
</script>


<style>


    .control-label {
        font-size: 15px;
        color: #357ebd;
    }

    .error {
        color: indianred;
        font-size: 13px;
    }

    .control-label {
        font-size: 15px;
    }

    label.error {
        float: left;
    }

    .contentErr {
        width: 50%;
        background: white;
        position: fixed;
        top: 20%;
        left: 25%;
        padding: 15px;
    }

    .ventana {
        width: 15%;
        height: 25%;
        padding: 1%;
        background-image: url(../../Resources/cargando.gif);
        background-size: 100% 100%;
        top: 40%;
        left: 42.5%;
        position: relative;
    }

    .Acordion {
        width: 820px;
    }

    .AcordionVentana {
        width: 100px;
        height: 100px;
    }

    .Error {
        color: #800000;
        font-size: small;
        font-weight: bold;
    }

    .Info {
        color: #800000;
        font-size: small;
        text-align: justify;
        font-weight: bold;
        width: 700px;
    }

    .Enca {
        width: 700px;
        text-align: center;
        background-color: #284775;
        color: #ffffff;
    }

    .ListCaja {
        width: 50%;
        border-collapse: collapse;
    }

    .th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    .td {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }

    .General {
        font-size: x-small;
        font-family: Calibri;
    }

    .Tamaño {
        height: 200px;
    }

 
    .btn-glyphicon {
        padding: 8px;
        background: #ffffff;
        margin-right: 4px;
    }

    .icon-btn {
        padding: 1px 15px 3px 2px;
        border-radius: 50px;
    }

    .text-secondary_asalud {
        font-family: "Century Gothic", "Century Gothic", Sans-Serif;
        color: #556da2;
    }

    input:read-only {
        background-color: #636363;
        color: #357ebd;
    }

    #tabla2 {
        font-family: "Century Gothic", "Century Gothic", Sans-Serif;
        font-size: 12px;
        margin: 10px;
        width: 100%;
        text-align: left;
        border-collapse: collapse;

    }

        #tabla2 th {
            font-weight: bold;
            padding: 8px;
            background: #636363;
            border-top: 4px solid #aabcfe;
            border-bottom: 1px solid #fff;
            color: #e8e8e8;
        }

        #tabla2 td {
            padding: 8px;
            background: #efefef;
            border-bottom: 2px solid #fff;
            color: #636363;
            border-top: 1px solid transparent;
        }

        #tabla2 tr:hover td {
            background: #bcbcbc;
            color: #1c1c1c;
        }

    .floatBlock {
        margin: 0 1.81em 0 0;
    }
</style>